//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Age: How old the member was when the Illumination occurred.
		///</summary>
		[ImplementPropertyType("age")]
		public int Age
		{
			get { return this.GetPropertyValue<int>("age"); }
		}

		///<summary>
		/// Country
		///</summary>
		[ImplementPropertyType("country")]
		public string Country
		{
			get { return this.GetPropertyValue<string>("country"); }
		}

		///<summary>
		/// First Name
		///</summary>
		[ImplementPropertyType("firstName")]
		public string FirstName
		{
			get { return this.GetPropertyValue<string>("firstName"); }
		}

		///<summary>
		/// Gender
		///</summary>
		[ImplementPropertyType("gender")]
		public int Gender
		{
			get { return this.GetPropertyValue<int>("gender"); }
		}

		///<summary>
		/// Illumination Story
		///</summary>
		[ImplementPropertyType("illuminationStory")]
		public IPublishedContent IlluminationStory
		{
			get { return this.GetPropertyValue<IPublishedContent>("illuminationStory"); }
		}

		///<summary>
		/// Last Name
		///</summary>
		[ImplementPropertyType("lastName")]
		public string LastName
		{
			get { return this.GetPropertyValue<string>("lastName"); }
		}

		///<summary>
		/// Illumination Story
		///</summary>
		[ImplementPropertyType("lblIlluminationStory")]
		public object LblIlluminationStory
		{
			get { return this.GetPropertyValue("lblIlluminationStory"); }
		}

		///<summary>
		/// Offered Prayers
		///</summary>
		[ImplementPropertyType("lblOfferedPrayers")]
		public object LblOfferedPrayers
		{
			get { return this.GetPropertyValue("lblOfferedPrayers"); }
		}

		///<summary>
		/// Prayer Requests
		///</summary>
		[ImplementPropertyType("lblPrayerRequests")]
		public object LblPrayerRequests
		{
			get { return this.GetPropertyValue("lblPrayerRequests"); }
		}

		///<summary>
		/// Prayer Requests: List of all of the member's personal prayer requests.
		///</summary>
		[ImplementPropertyType("prayerRequests")]
		public Newtonsoft.Json.Linq.JToken PrayerRequests
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("prayerRequests"); }
		}

		///<summary>
		/// Prayers Offered For: List of all prayers that the member offered to pray for.
		///</summary>
		[ImplementPropertyType("prayersOfferedFor")]
		public Newtonsoft.Json.Linq.JToken PrayersOfferedFor
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("prayersOfferedFor"); }
		}

		///<summary>
		/// Race
		///</summary>
		[ImplementPropertyType("race")]
		public IEnumerable<string> Race
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("race"); }
		}

		///<summary>
		/// Religion
		///</summary>
		[ImplementPropertyType("religion")]
		public string Religion
		{
			get { return this.GetPropertyValue<string>("religion"); }
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}
}
