//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Prayer List</summary>
	[PublishedContentModel("prayerList")]
	public partial class PrayerList : PublishedContentModel, INavigation, ISEO
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "prayerList";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PrayerList(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PrayerList, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Candle- 10%
		///</summary>
		[ImplementPropertyType("candle10")]
		public IPublishedContent Candle10
		{
			get { return this.GetPropertyValue<IPublishedContent>("candle10"); }
		}

		///<summary>
		/// Candle- 100%
		///</summary>
		[ImplementPropertyType("candle100")]
		public IPublishedContent Candle100
		{
			get { return this.GetPropertyValue<IPublishedContent>("candle100"); }
		}

		///<summary>
		/// Candle- 20%
		///</summary>
		[ImplementPropertyType("candle20")]
		public IPublishedContent Candle20
		{
			get { return this.GetPropertyValue<IPublishedContent>("candle20"); }
		}

		///<summary>
		/// Candle- 30%
		///</summary>
		[ImplementPropertyType("candle30")]
		public IPublishedContent Candle30
		{
			get { return this.GetPropertyValue<IPublishedContent>("candle30"); }
		}

		///<summary>
		/// Candle- 40%
		///</summary>
		[ImplementPropertyType("candle40")]
		public IPublishedContent Candle40
		{
			get { return this.GetPropertyValue<IPublishedContent>("candle40"); }
		}

		///<summary>
		/// Candle- 50%
		///</summary>
		[ImplementPropertyType("candle50")]
		public IPublishedContent Candle50
		{
			get { return this.GetPropertyValue<IPublishedContent>("candle50"); }
		}

		///<summary>
		/// Candle- 60%
		///</summary>
		[ImplementPropertyType("candle60")]
		public IPublishedContent Candle60
		{
			get { return this.GetPropertyValue<IPublishedContent>("candle60"); }
		}

		///<summary>
		/// Candle- 70%
		///</summary>
		[ImplementPropertyType("candle70")]
		public IPublishedContent Candle70
		{
			get { return this.GetPropertyValue<IPublishedContent>("candle70"); }
		}

		///<summary>
		/// Candle- 80%
		///</summary>
		[ImplementPropertyType("candle80")]
		public IPublishedContent Candle80
		{
			get { return this.GetPropertyValue<IPublishedContent>("candle80"); }
		}

		///<summary>
		/// Candle- 90%
		///</summary>
		[ImplementPropertyType("candle90")]
		public IPublishedContent Candle90
		{
			get { return this.GetPropertyValue<IPublishedContent>("candle90"); }
		}

		///<summary>
		/// Candle- Answered
		///</summary>
		[ImplementPropertyType("candleAnswered")]
		public IPublishedContent CandleAnswered
		{
			get { return this.GetPropertyValue<IPublishedContent>("candleAnswered"); }
		}

		///<summary>
		/// Candle Out
		///</summary>
		[ImplementPropertyType("candleOut")]
		public IPublishedContent CandleOut
		{
			get { return this.GetPropertyValue<IPublishedContent>("candleOut"); }
		}

		///<summary>
		/// Form Picker: Used to report prayers for review.
		///</summary>
		[ImplementPropertyType("formPicker")]
		public formulate.app.Types.ConfiguredFormInfo FormPicker
		{
			get { return this.GetPropertyValue<formulate.app.Types.ConfiguredFormInfo>("formPicker"); }
		}

		///<summary>
		/// Hide Children from Navigation: Displays page in menu, but hides the children.
		///</summary>
		[ImplementPropertyType("hideChildrenFromNavigation")]
		public bool HideChildrenFromNavigation
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetHideChildrenFromNavigation(this); }
		}

		///<summary>
		/// Logged-In Item Only: Item that only is visible in navigation when the user is logged in.
		///</summary>
		[ImplementPropertyType("loggedInItemOnly")]
		public bool LoggedInItemOnly
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetLoggedInItemOnly(this); }
		}

		///<summary>
		/// Logged-Out Item Only: Item that is only visible in navigation when the user is logged out
		///</summary>
		[ImplementPropertyType("loggedOutItemOnly")]
		public bool LoggedOutItemOnly
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetLoggedOutItemOnly(this); }
		}

		///<summary>
		/// Show in Minor Navigation: Show link in minor navigation
		///</summary>
		[ImplementPropertyType("showInMinorNavigation")]
		public bool ShowInMinorNavigation
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetShowInMinorNavigation(this); }
		}

		///<summary>
		/// Hide from Main Navigation: Prevents page from appearing in the menu.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.Navigation.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Meta Robots
		///</summary>
		[ImplementPropertyType("metaRobots")]
		public object MetaRobots
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetMetaRobots(this); }
		}

		///<summary>
		/// Redirects
		///</summary>
		[ImplementPropertyType("redirects")]
		public object Redirects
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetRedirects(this); }
		}

		///<summary>
		/// SEO Checker
		///</summary>
		[ImplementPropertyType("sEOChecker")]
		public SEOChecker.MVC.MetaData SEochecker
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetSEochecker(this); }
		}

		///<summary>
		/// XMLSitemap
		///</summary>
		[ImplementPropertyType("xMLSitemap")]
		public object XMlsitemap
		{
			get { return Umbraco.Web.PublishedContentModels.SEO.GetXMlsitemap(this); }
		}
	}
}
