//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Webmaster Message</summary>
	[PublishedContentModel("webmasterMessage")]
	public partial class WebmasterMessage : PublishedContentModel, IMessage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "webmasterMessage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public WebmasterMessage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<WebmasterMessage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetContent(this); }
		}

		///<summary>
		/// Date of Message(s): *Optional: Select all dates that apply to the messages.
		///</summary>
		[ImplementPropertyType("dateOfMessages")]
		public List<DateTime> DateOfMessages
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetDateOfMessages(this); }
		}

		///<summary>
		/// Meta Robots
		///</summary>
		[ImplementPropertyType("metaRobots")]
		public object MetaRobots
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetMetaRobots(this); }
		}

		///<summary>
		/// Page Content
		///</summary>
		[ImplementPropertyType("pageContent")]
		public object PageContent
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetPageContent(this); }
		}

		///<summary>
		/// Publish Date
		///</summary>
		[ImplementPropertyType("publishDate")]
		public DateTime PublishDate
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetPublishDate(this); }
		}

		///<summary>
		/// Publish Info
		///</summary>
		[ImplementPropertyType("publishInfo")]
		public object PublishInfo
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetPublishInfo(this); }
		}

		///<summary>
		/// Redirects
		///</summary>
		[ImplementPropertyType("redirects")]
		public object Redirects
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetRedirects(this); }
		}

		///<summary>
		/// SEO Checker
		///</summary>
		[ImplementPropertyType("sEOChecker")]
		public SEOChecker.MVC.MetaData SEochecker
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetSEochecker(this); }
		}

		///<summary>
		/// Subtitle: *Optional- Displayed under the page title.
		///</summary>
		[ImplementPropertyType("subtitle")]
		public string Subtitle
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetSubtitle(this); }
		}

		///<summary>
		/// XMLSitemap
		///</summary>
		[ImplementPropertyType("xMLSitemap")]
		public object XMlsitemap
		{
			get { return Umbraco.Web.PublishedContentModels.Message.GetXMlsitemap(this); }
		}
	}
}
